package com.deviceintelligence.utils

import android.content.Context
import androidx.compose.runtime.mutableStateOf

data class AppStrings(
    // Dashboard
    val systemHealth: String,
    val performance: String,
    val memory: String,
    val battery: String,
    val cpu: String,
    val storage: String,
    val temperature: String,
    val device: String,
    val monitorOnly: String,

    // Security
    val securityLevel: String,
    val activeThreats: String,
    val scanNow: String,
    val aiAnalysis: String,
    val riskLevel: String,
    val behaviorScore: String,
    val recommendations: String,
    val noThreatsDetected: String,
    val resolve: String,
    val threat: String,
    val critical: String,
    val high: String,
    val medium: String,
    val low: String,
    val total: String,

    // Blockchain
    val chainHealth: String,
    val blocks: String,
    val status: String,
    val valid: String,
    val invalid: String,
    val cloudSync: String,
    val sync: String,
    val smartContract: String,
    val autoResponse: String,
    val enabled: String,
    val disabled: String,
    val alertLevel: String,
    val blockHistory: String,
    val verifyChain: String,

    // Settings
    val settings: String,
    val notifications: String,
    val enableSystemNotifications: String,
    val darkMode: String,
    val followSystemSettings: String,
    val storageOptimization: String,
    val autoCleanCache: String,
    val securityChecks: String,
    val regularSecurityScanning: String,
    val monitoring: String,
    val backgroundMonitoring: String,
    val realtimeSystemMonitoring: String,
    val securityAi: String,
    val threatAlerts: String,
    val alertOnDetectedThreats: String,
    val permissionMonitoring: String,
    val monitorAppPermissions: String,
    val automationBlockchain: String,
    val autoOptimization: String,
    val automaticDeviceOptimization: String,
    val cloudSyncDesc: String,
    val syncSecurityRecords: String,
    val about: String,
    val appVersion: String,
    val adaptiveDeviceIntelligence: String,
    val checkForUpdates: String,
    val latest: String,
    val language: String,
    val selectLanguage: String,
    val english: String,
    val korean: String,

    // Advisor
    val advisor: String,
    val optimization: String,
    val recommendations_: String,

    // Predictor
    val predictor: String,
    val performanceForecast: String,

    // Common
    val dashboard: String,
    val security: String,
    val blockchain: String,
    val back: String,
    val notificationsEnabled: String,
    val notificationsDisabled: String,
    val darkModeEnabled: String,
    val storageOptimizationEnabled: String,
    val storageOptimizationDisabled: String,
    val securityChecksEnabled: String,
    val securityChecksDisabled: String,
    val backgroundMonitoringEnabled: String,
    val backgroundMonitoringDisabled: String,
    val threatAlertsEnabled: String,
    val threatAlertsDisabled: String,
    val permissionMonitoringEnabled: String,
    val permissionMonitoringDisabled: String,
    val autoOptimizationEnabled: String,
    val autoOptimizationDisabled: String,
    val cloudSyncEnabled: String,
    val cloudSyncDisabled: String,
    val checkingForUpdates: String,
    val languageChanged: String,
    val analyzing: String,
    val syncing: String,
    val chainVerification: String,
    val markedAsResolved: String,
    val thermal: String,
    val drain: String,
    val cpuLoad: String,
    val clearCacheMemory: String,
    val disableBackgroundSync: String,
    val updateApps: String,
    val applied: String,
    val applyOptimization: String,
    val recommend: String,
    val safeAutoOptimize: String,
    val adaptiveAutonomous: String,
    val enableEnergySaver: String,
    val energySaverEnabled: String,
    val appUpdates: String,
)

object LocalizedStrings {
    private val englishStrings = AppStrings(
        systemHealth = "System Health",
        performance = "Performance",
        memory = "Memory",
        battery = "Battery",
        cpu = "CPU",
        storage = "Storage",
        temperature = "Temperature",
        device = "Device",
        monitorOnly = "Monitor Only",

        securityLevel = "Security Level",
        activeThreats = "Active Threats",
        scanNow = "Scan Now",
        aiAnalysis = "AI Analysis",
        riskLevel = "Risk Level",
        behaviorScore = "Behavior Score",
        recommendations = "Recommendations",
        noThreatsDetected = "No threats detected",
        resolve = "Resolve",
        threat = "Threat",
        critical = "Critical",
        high = "High",
        medium = "Medium",
        low = "Low",
        total = "Total",

        chainHealth = "Chain Health",
        blocks = "Blocks",
        status = "Status",
        valid = "Valid",
        invalid = "Invalid",
        cloudSync = "Cloud Sync",
        sync = "Sync",
        smartContract = "Smart Contract",
        autoResponse = "Auto Response",
        enabled = "Enabled",
        disabled = "Disabled",
        alertLevel = "Alert Level",
        blockHistory = "Block History",
        verifyChain = "Verify Chain",

        settings = "Settings",
        notifications = "Notifications",
        enableSystemNotifications = "Enable system notifications",
        darkMode = "Dark Mode",
        followSystemSettings = "Follows system settings",
        storageOptimization = "Storage Optimization",
        autoCleanCache = "Auto-clean cache and temp files",
        securityChecks = "Security Checks",
        regularSecurityScanning = "Regular security scanning",
        monitoring = "Monitoring",
        backgroundMonitoring = "Background Monitoring",
        realtimeSystemMonitoring = "Real-time system monitoring",
        securityAi = "Security & AI",
        threatAlerts = "Threat Alerts",
        alertOnDetectedThreats = "Alert on detected threats",
        permissionMonitoring = "Permission Monitoring",
        monitorAppPermissions = "Monitor app permission usage",
        automationBlockchain = "Automation & Blockchain",
        autoOptimization = "Auto Optimization",
        automaticDeviceOptimization = "Automatic device optimization",
        cloudSyncDesc = "Sync security records to cloud",
        syncSecurityRecords = "Sync security records to cloud",
        about = "About",
        appVersion = "App Version",
        adaptiveDeviceIntelligence = "Adaptive Device Intelligence Platform",
        checkForUpdates = "Check for Updates",
        latest = "Latest",
        language = "Language",
        selectLanguage = "Select Language",
        english = "English",
        korean = "한국어",

        advisor = "Advisor",
        optimization = "Optimization",
        recommendations_ = "Recommendations",

        predictor = "Predictor",
        performanceForecast = "Performance Forecast",

        dashboard = "Dashboard",
        security = "Security",
        blockchain = "Blockchain",
        back = "Back",
        notificationsEnabled = "Notifications enabled",
        notificationsDisabled = "Notifications disabled",
        darkModeEnabled = "Dark mode setting (follows system settings)",
        storageOptimizationEnabled = "Storage optimization enabled",
        storageOptimizationDisabled = "Storage optimization disabled",
        securityChecksEnabled = "Security checks enabled",
        securityChecksDisabled = "Security checks disabled",
        backgroundMonitoringEnabled = "Background monitoring enabled",
        backgroundMonitoringDisabled = "Background monitoring disabled",
        threatAlertsEnabled = "Threat alerts enabled",
        threatAlertsDisabled = "Threat alerts disabled",
        permissionMonitoringEnabled = "Permission monitoring enabled",
        permissionMonitoringDisabled = "Permission monitoring disabled",
        autoOptimizationEnabled = "Auto optimization enabled",
        autoOptimizationDisabled = "Auto optimization disabled",
        cloudSyncEnabled = "Cloud sync enabled",
        cloudSyncDisabled = "Cloud sync disabled",
        checkingForUpdates = "Checking for updates...",
        languageChanged = "Language changed",
        analyzing = "Analyzing...",
        syncing = "Syncing...",
        chainVerification = "Chain verification...",
        markedAsResolved = "Threat marked as resolved",
        thermal = "Thermal",
        drain = "Drain",
        cpuLoad = "CPU Load",
        clearCacheMemory = "Clear Cache Memory",
        disableBackgroundSync = "Disable Background Sync",
        updateApps = "Update Apps",
        applied = "Applied",
        applyOptimization = "Apply Optimization",
        recommend = "Recommend",
        safeAutoOptimize = "Safe Auto-Optimize",
        adaptiveAutonomous = "Adaptive Autonomous",
        enableEnergySaver = "Enable Energy Saver",
        energySaverEnabled = "Energy Saver Enabled",
        appUpdates = "App updates applied! Performance improved",
    )

    private val koreanStrings = AppStrings(
        systemHealth = "시스템 상태",
        performance = "성능",
        memory = "메모리",
        battery = "배터리",
        cpu = "CPU",
        storage = "저장소",
        temperature = "온도",
        device = "기기",
        monitorOnly = "모니터링만",

        securityLevel = "보안 수준",
        activeThreats = "활성 위협",
        scanNow = "지금 스캔",
        aiAnalysis = "AI 분석",
        riskLevel = "위험 수준",
        behaviorScore = "행동 점수",
        recommendations = "권장사항",
        noThreatsDetected = "위협이 감지되지 않음",
        resolve = "해결",
        threat = "위협",
        critical = "심각",
        high = "높음",
        medium = "중간",
        low = "낮음",
        total = "전체",

        chainHealth = "체인 건강",
        blocks = "블록",
        status = "상태",
        valid = "유효",
        invalid = "무효",
        cloudSync = "클라우드 동기화",
        sync = "동기화",
        smartContract = "스마트 계약",
        autoResponse = "자동 응답",
        enabled = "활성화",
        disabled = "비활성화",
        alertLevel = "경보 수준",
        blockHistory = "블록 기록",
        verifyChain = "체인 검증",

        settings = "설정",
        notifications = "알림",
        enableSystemNotifications = "시스템 알림 활성화",
        darkMode = "다크 모드",
        followSystemSettings = "시스템 설정 따름",
        storageOptimization = "저장소 최적화",
        autoCleanCache = "캐시 및 임시 파일 자동 정리",
        securityChecks = "보안 검사",
        regularSecurityScanning = "정기적 보안 스캔",
        monitoring = "모니터링",
        backgroundMonitoring = "백그라운드 모니터링",
        realtimeSystemMonitoring = "실시간 시스템 모니터링",
        securityAi = "보안 & AI",
        threatAlerts = "위협 경보",
        alertOnDetectedThreats = "위협 감지 시 경보",
        permissionMonitoring = "권한 모니터링",
        monitorAppPermissions = "앱 권한 사용 모니터링",
        automationBlockchain = "자동화 & 블록체인",
        autoOptimization = "자동 최적화",
        automaticDeviceOptimization = "자동 기기 최적화",
        cloudSyncDesc = "보안 기록을 클라우드에 동기화",
        syncSecurityRecords = "보안 기록을 클라우드에 동기화",
        about = "정보",
        appVersion = "앱 버전",
        adaptiveDeviceIntelligence = "적응형 기기 지능 플랫폼",
        checkForUpdates = "업데이트 확인",
        latest = "최신",
        language = "언어",
        selectLanguage = "언어 선택",
        english = "English",
        korean = "한국어",

        advisor = "어드바이저",
        optimization = "최적화",
        recommendations_ = "권장사항",

        predictor = "예측기",
        performanceForecast = "성능 예측",

        dashboard = "대시보드",
        security = "보안",
        blockchain = "블록체인",
        back = "뒤로",
        notificationsEnabled = "알림 활성화됨",
        notificationsDisabled = "알림 비활성화됨",
        darkModeEnabled = "다크 모드 설정 (시스템 설정 따름)",
        storageOptimizationEnabled = "저장소 최적화 활성화됨",
        storageOptimizationDisabled = "저장소 최적화 비활성화됨",
        securityChecksEnabled = "보안 검사 활성화됨",
        securityChecksDisabled = "보안 검사 비활성화됨",
        backgroundMonitoringEnabled = "백그라운드 모니터링 활성화됨",
        backgroundMonitoringDisabled = "백그라운드 모니터링 비활성화됨",
        threatAlertsEnabled = "위협 경보 활성화됨",
        threatAlertsDisabled = "위협 경보 비활성화됨",
        permissionMonitoringEnabled = "권한 모니터링 활성화됨",
        permissionMonitoringDisabled = "권한 모니터링 비활성화됨",
        autoOptimizationEnabled = "자동 최적화 활성화됨",
        autoOptimizationDisabled = "자동 최적화 비활성화됨",
        cloudSyncEnabled = "클라우드 동기화 활성화됨",
        cloudSyncDisabled = "클라우드 동기화 비활성화됨",
        checkingForUpdates = "업데이트 확인 중...",
        languageChanged = "언어 변경됨",
        analyzing = "분석 중...",
        syncing = "동기화 중...",
        chainVerification = "체인 검증 중...",
        markedAsResolved = "위협이 해결됨으로 표시됨",
        thermal = "열",
        drain = "소비",
        cpuLoad = "CPU 부하",
        clearCacheMemory = "캐시 메모리 삭제",
        disableBackgroundSync = "백그라운드 동기화 비활성화",
        updateApps = "앱 업데이트",
        applied = "적용됨",
        applyOptimization = "최적화 적용",
        recommend = "권장",
        safeAutoOptimize = "안전한 자동 최적화",
        adaptiveAutonomous = "적응형 자율",
        enableEnergySaver = "절전 모드 활성화",
        energySaverEnabled = "절전 모드가 활성화됨",
        appUpdates = "앱 업데이트 완료! 성능 개선됨",
    )

    fun getStrings(language: String): AppStrings {
        return when (language) {
            "ko" -> koreanStrings
            else -> englishStrings
        }
    }
}

// 전역 언어 상태 (Composable에서 사용)
val currentLanguage = mutableStateOf("en")

fun getCurrentStrings(): AppStrings {
    return LocalizedStrings.getStrings(currentLanguage.value)
}
